function values = getExportValues(patient, study, series, file, sequenceNumber)
% values = getExportValues(patient, study, series, file, sequenceNumber)
%
% ** REQUIRED BY GIANT **
%
% uses the patient, study, series, and file to determine what to print in
% each cell for a row for the csv export

% EX:

values = struct(...
    'patientId', patient.patientId,...
    'patientSex', file.dicomInfo.PatientSex,...
    'patientDob', '',... %will be manually entered into .csv
    'sequenceNumber', sequenceNumber,...
    'studyDate', file.date.stringForCsv(),...
    'modality', file.dicomInfo.Modality,...
    'studyName', study.name,...
    'seriesName', series.name,...
    'fileName', file.name,...
    'field1', file.field1,...
    'field2', file.field2,...
    'field3', file.field3);

end
