function [ header ] = getHeader()
% [ header ] = getHeader()
%
% ** REQUIRED BY GIANT **
%
% returns the header for the .csv export file as a cell array
% can be multiple lines if need be

% EX:

topHeader = { ...
    'Patient Id',...
    'Patient Sex',...
    'Patient DOB (MMM-YY)',...
    'Sequence Number',...
    'Study Date (DD-MMM-YY)',...
    'Age at Acquisition (Months)',...
    'Modality',...
    'Study Name',...
    'Series Name',...
    'File Name',...
    'Field Values','',''};

subHeader = { '','','','','','','','','','', 'Field 1', 'Field 2', 'Field 3'};

header = [topHeader; subHeader];


end

