function [] = printToFile(fileId, lineNumber, values, newline, delim)
% printToFile(fileId, lineNumber, values, newline, delim)
%
% ** REQUIRED BY GIANT **
%
% prints the values (given in struct 'values') for a single line into file at fileId. The
% lineNumber given is used for an excel formulae that may need to be
% written. newLine and delim (delimiter) values are given for ease of
% change in case a different format is needed

% EX:

dobCell = ['C', num2str(lineNumber)];
studyDateCell = ['E', num2str(lineNumber)];

ageFormula = ['=(MONTH(', studyDateCell ,') - MONTH(', dobCell, '))+(YEAR(', studyDateCell, ') - YEAR(', dobCell, '))*12'];

% formats follow those specified for sprintf, printf, etc.
format = struct(...
    'patientId', '%s',...
    'patientSex', '%s',...
    'patientDob', '%s',...
    'sequenceNumber', '%d',...
    'studyDate', '%s',...
    'ageInMonths', '%s',... %since formula is string
    'modality', '%s',...
    'studyName', '%s',...
    'seriesName', '%s',...
    'fileName', '%s',...
    'field1', '%6.1f',...
    'field2', '%6.1f',...
    'field3', '%6.1f');

line = strcat(...
    sprintf(format.patientId, values.patientId), delim,...
    sprintf(format.patientSex, values.patientSex), delim,...
    sprintf(format.patientDob, values.patientDob), delim,...
    sprintf(format.sequenceNumber, values.sequenceNumber), delim,...
    sprintf(format.studyDate, values.studyDate), delim,...
    sprintf(format.ageInMonths, ageFormula), delim,...
    sprintf(format.modality, values.modality), delim,...
    sprintf(format.studyName, values.studyName), delim,...
    sprintf(format.seriesName, values.seriesName), delim,...
    sprintf(format.fileName, values.fileName), delim,...
    sprintf(format.field1, values.field1), delim,...
    sprintf(format.field2, values.field2), delim,...
    sprintf(format.field3, values.field3));

fprintf(fileId, line);

fprintf(fileId, newline);
    
end

