function [ values ] = setFields(cellValues)
%[ values ] = setFields(cellValues)
%
% ** REQUIRED BY GIANT **
%
% takes in the values of a row cells read in, in order, and returns them,
% conveinently stored in a struct
%
% EX:

values = struct(...
    'patientId', cellValues{1},...
    'patientSex', cellValues{2},...
    'patientDob', cellValues{3},... 
    'sequenceNumber', str2double(cellValues{4}),...
    'studyDate', cellValues{5},...
    'modality', cellValues{7},... % cellValues{6} skipped; age formula (must be updated to have proper cell references)
    'studyName', cellValues{8},...
    'seriesName', cellValues{9},...
    'fileName', cellValues{10},...
    'field1', str2double(cellValues{11}),...
    'field2', str2double(cellValues{12}),...
    'field3', str2double(cellValues{13}));


end

